USE [master]
GO

/****** Object:  Database [DB_Ban_Hang]    Script Date: 02/07/2024 8:25:42 CH ******/
CREATE DATABASE [DB_Ban_Hang]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_Ban_Hang', FILENAME = N'C:\SQL2019\MSSQL15.SQLEXPRESS01\MSSQL\DATA\DB_Ban_Hang.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_Ban_Hang_log', FILENAME = N'C:\SQL2019\MSSQL15.SQLEXPRESS01\MSSQL\DATA\DB_Ban_Hang_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_Ban_Hang].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_Ban_Hang] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_Ban_Hang] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_Ban_Hang] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_Ban_Hang] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_Ban_Hang] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_Ban_Hang] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [DB_Ban_Hang] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_Ban_Hang] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_Ban_Hang] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_Ban_Hang] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_Ban_Hang] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_Ban_Hang] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_Ban_Hang] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_Ban_Hang] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_Ban_Hang] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DB_Ban_Hang] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_Ban_Hang] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_Ban_Hang] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_Ban_Hang] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_Ban_Hang] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_Ban_Hang] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_Ban_Hang] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_Ban_Hang] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DB_Ban_Hang] SET  MULTI_USER 
GO

ALTER DATABASE [DB_Ban_Hang] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_Ban_Hang] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_Ban_Hang] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_Ban_Hang] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DB_Ban_Hang] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_Ban_Hang] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DB_Ban_Hang] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DB_Ban_Hang] SET  READ_WRITE 
GO


